name: New contributor message

on:
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      # Pinned to v2.0
      - uses: deborah-digges/new-pull-request-comment-action@224c179a9e23f65ec50ff3240b8716369dc415d7
        with:
          access-token: ${{ secrets.GITHUBB_TOKEN }}
          message: |
            Hello @{}! Thank you for your contribution 💪
            As it's your first contribution be sure to test on different environments, different database structures and make sure your code follows good [Python practices](https://www.python.org/dev/peps/pep-0008/) and the [Django Documentation](https://docs.djangoproject.com/).
            If you have any design or process questions then you can ask in the [RagCP discussions](https://github.com/Freyja-Folkvangr/ragpycp/discussions).
            Welcome aboard ⛵️!
